### ISSUE TITLE
ssdp:byebye not sent 

### ISSUE THREAD

**Issue by PatrLind** [koron/go-ssdp#11]
ssdp:byebye is not sent if called right before Close()
A workaround is to add a Sleep() call before close.
Example:
```
ssdpAdvertiser.Bye()
time.Sleep(100 * time.Millisecond)
ssdpAdvertiser.Close()
```

**Comment by koron** [comment]
the cause of this problem is `Close()` ignores sending queue.

**Comment by koron** [comment]
#11 is trial for this.

**Comment by andig** [comment]
My add-on issue here would be that advertiser should send bye when closing without explicit call to close. This would be similar to sending ssdp:alive when advertiser is created?
