### ISSUE TITLE
How to send search responses?

### ISSUE THREAD

**Issue by andig** [koron/go-ssdp#17]
Implementing the monitor endpoint, I need to response to search requests. The search responses are similar to NOTIFY messages, but must contain ST instead of NT. I couldn't figure out how to send these responses using this package?

**UPDATE** refers to https://tools.ietf.org/html/draft-cai-ssdp-v1-03#page-10

**Comment by andig** [comment]
@koron if you would accept a PR I'd be happy to implement this. Just need to understand if that's in line with your plans as I'm new to SSDP.

**Comment by andig** [comment]
I've just realised that using the Advertiser, the search responses are actually being sent: https://github.com/koron/go-ssdp/blob/master/advertise.go#L39. So to be in line with announce and byebye all that's needed would be the ability to send these standalone.

**Comment by koron** [comment]
i have merged https://github.com/koron/go-ssdp/pull/14.
does it work for you, enough?

**Comment by andig** [comment]
Thats perfekt for my purposes, thank you!
