### ISSUE TITLE
Error when installing

### ISSUE THREAD

**Issue by b101marc** [koron/go-ssdp#23]
When running `go get github.com/koron/go-ssdp` I get the following in return.

`go/src/github.com/koron/go-ssdp/monitor.go:47:20: undefined: errors.Is`

Any guidance appreciated.

**Comment by koron** [comment]
which version of go do you use?
`errors.Is` is introduced from Go 1.13.

and koron/go-ssdp is written for Go 1.13 or later
(See https://github.com/koron/go-ssdp/blob/ee6c24884ce04dd9f0fcea96f2d790904d6c98a3/go.mod#L3)
so you should upgrade Go to use this.
