### ISSUE TITLE
Calling net.InterfaceAddrs() results in error route ip+net: netlinkrib: permission denied when embedded in Android app targetting SDK 30

### ISSUE THREAD

**Issue by alexballas** [koron/go-ssdp#32]
This is caused by https://github.com/golang/go/issues/40569
There are some workaround in the upstream ticket but nothing solid so far. Just raising this for your visibility.

My application is also available on Android so this is causing issues as multicast discovery is not working.

I raised this for your visibility. Feel free to resolve it accordingly.

**Comment by alexballas** [comment]
I managed to workaround it. Will push a PR here when the time permits.

**Comment by alexballas** [comment]
https://github.com/koron/go-ssdp/pull/33

**Comment by koron** [comment]
i supposed #36 will solve this in a generic way.
